plugins {
    id 'com.android.library'
}

android {
    namespace 'com.brouken.player.core.library'
    compileSdk 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }

    lint {
        disable 'MissingTranslation'
        disable 'UnsafeOptInUsageError'
    }
}

dependencies {
    def room_version = '2.6.1'

    api "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    api 'androidx.lifecycle:lifecycle-livedata:2.8.7'
    api "androidx.annotation:annotation:1.9.1"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.room:room-testing:2.6.1'
    testImplementation 'org.robolectric:robolectric:4.13'
    testImplementation 'androidx.test:core:1.6.1'
}
