plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.brouken.player'
    compileSdk 35
    ndkVersion '21.4.7075529'

    defaultConfig {
        def abiFilter = project.findProperty("abiFilter")
        applicationId "com.brouken.player"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 197
        versionName "0.${versionCode}"
        archivesBaseName = "Lucent.v${versionName}"
        if (abiFilter) {
            def abiCodeMap = ["x86": 1, "x86_64": 2, "armeabi-v7a": 3, "arm64-v8a": 4]
            versionCode = versionCode * 10 + abiCodeMap[abiFilter]
            ndk {
                abiFilters abiFilter
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            //proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // No signingConfig: builds will be unsigned
        }
    }
    flavorDimensions "targetSdk", "distribution"
    productFlavors {
        latest {
            dimension "targetSdk"
        }
        legacy {
            dimension "targetSdk"
            versionCode = defaultConfig.versionCode + 1_000_000
            versionNameSuffix "-legacy"
            targetSdkVersion 29
        }

        universal {
            dimension "distribution"
        }
        amazon {
            dimension "distribution"
        }
        accrescent {
            dimension "distribution"
        }
    }
    variantFilter { variant ->
        def names = variant.flavors*.name
        if (names.contains("legacy") && (names.contains("amazon") || names.contains("accrescent"))) {
            setIgnore(true)
        }
    }
    applicationVariants.all { variant ->
        if (variant.buildType.name == "release" && variant.flavorName == "latestUniversal") {
            variant.outputs.all { output ->
                output.outputFileName = "${archivesBaseName}.apk"
            }
        }
        if (variant.buildType.name == "release" && variant.flavorName == "legacyUniversal") {
            variant.outputs.all { output ->
                output.outputFileName = "${archivesBaseName}-legacy.apk"
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        buildConfig = true
        compose true
    }
    lint {
        disable 'MissingTranslation'
        disable 'UnsafeOptInUsageError'
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }
}

dependencies {
    def media3_version = '1.8.0'
    def androidxCoreVersion = '1.8.0'
    implementation "androidx.media3:media3-session:$media3_version"
    implementation "androidx.media3:media3-datasource:$media3_version"
    implementation "androidx.media3:media3-decoder:$media3_version"
    implementation "androidx.media3:media3-common:$media3_version"
    implementation "androidx.media3:media3-container:$media3_version"
    implementation("androidx.media3:media3-exoplayer-dash:$media3_version") {
        exclude group: "androidx.media3", module: "media3-exoplayer"
    }
    implementation("androidx.media3:media3-exoplayer-hls:$media3_version") {
        exclude group: "androidx.media3", module: "media3-exoplayer"
    }
    implementation("androidx.media3:media3-exoplayer-smoothstreaming:$media3_version") {
        exclude group: "androidx.media3", module: "media3-exoplayer"
    }
    implementation("androidx.media3:media3-exoplayer-rtsp:$media3_version") {
        exclude group: "androidx.media3", module: "media3-exoplayer"
    }
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.getkeepsafe.taptargetview:taptargetview:1.13.3'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.3.0'
    implementation "androidx.core:core:$androidxCoreVersion"
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.squareup.okhttp3:okhttp:5.0.0'
    implementation 'com.sigpwned:chardet4j:77.1.0'
    implementation project(path: ':doubletapplayerview')
    implementation project(path: ':android-file-chooser')
    implementation project(path: ':core-playback')
    implementation project(path: ':core-gestures')
    implementation project(path: ':core-design-system')
    implementation project(path: ':feature-player-ui')
    implementation project(path: ':core-library')
    implementation project(path: ':feature-library-ui')

    def composeBom = platform('androidx.compose:compose-bom:2025.06.01')
    implementation composeBom
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.compose.runtime:runtime-livedata'
    implementation 'androidx.activity:activity-compose:1.9.3'
    implementation fileTree(dir: "libs", include: ["lib-*.aar"])

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.13'
    testImplementation 'androidx.test:core:1.6.1'
}
