name: Android Build APK

on:
  push:
    branches:
      - main
    tags:
      - 'v0.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build release (APK + AAB)
        run: |
          echo "Running Gradle assembleRelease and bundleRelease..."
          ./gradlew assembleRelease bundleRelease

      - name: Collect artifacts (APK / AAB) into a single folder
        run: |
          mkdir -p release || true
          find app/build/outputs -type f \( -iname "*.apk" -o -iname "*.aab" \) -print -exec cp {} release/ \; || true
          ls -la release || true

      - name: Make a zip for easy sideloading (app-release.zip)
        run: |
          rm -f app-release.zip || true
          if [ -d release ] && [ "$(ls -A release)" ]; then
            cd release
            zip -r ../app-release.zip ./*
            cd ..
            echo "Created app-release.zip with contents:"
            unzip -l app-release.zip
          else
            echo "No APK / AAB found to zip. Creating an empty zip to avoid step failure."
            zip -r app-release.zip --filesync --quiet --recurse-paths -- *
          fi

      - name: Upload zipped release artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-zip
          path: app-release.zip

      - name: Create GitHub Release and attach zip (only for tag runs)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-release.zip
          prerelease: true
          draft: true
