name: Android Build APK
on:
  push:
    branches:
      - main
    tags:
      - 'v0.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: |
          echo "Building app module release APK..."
          ./gradlew :app:assembleRelease

      - name: Collect installable APK(s)
        run: |
          mkdir -p release || true
          # Copy only app module release APK(s)
          find app/build/outputs/apk/release -type f -name "*release.apk" -exec cp {} release/ \;
          ls -la release

      - name: Make a zip for easy sideloading
        run: |
          rm -f app-release.zip || true
          cd release
          zip -r ../app-release.zip ./*
          cd ..
          echo "Created app-release.zip with contents:"
          unzip -l app-release.zip

      - name: Upload zipped release artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-zip
          path: app-release.zip

      - name: Create GitHub Release and attach zip (only for tag runs)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.zip
          prerelease: true
          draft: true
